# Change these first
owner: tunatuna1733 # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: LoL Tools Frontend
    url: https://lol.tunatuna.dev
  - name: LoL Tools Backend
    url: https://urgot.tunatuna.dev
  - name: LoL Tools Discord Backend
    url: https://akali.tunatuna.dev
    expectedStatusCodes:
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tunatuna.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: LoL Tools Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
